version: '3.5'
services:
  mongodb-service:
    container_name: mongodb
    image: mongo
    ports:
      - '8000:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "1234"
