name: Story Template
description: Eine Story besteht aus mehreren Aufgaben.
title: ""
labels: ["Story"]
projects: ["SE-TINF22B2/9"]
body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Fasse zusammen, worum es in der Story und den Tasks geht.
  - type: textarea
    id: tasks
    attributes:
      label: Aufgaben
      description: Definiere hier die Aufgaben dieser Story.
      value: |
        - [ ] Task 1
        - [ ] Task 2
  - type: textarea
    id: criteria
    attributes:
      label: Kriterien für die Annahme
      description: Definiere hier die Kriterien, die erfüllt werden müssen.
      value: |
        - Kriterium 1
        - Kriterium 2
  
